env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
plugins:
  - '@typescript-eslint'
  - 'jest'
rules: {
  - "jest/no-disabled-tests": "warn",
  - "jest/no-focused-tests": "error",
  - "jest/no-identical-title": "error",
  - "jest/prefer-to-have-length": "warn",
  - "jest/valid-expect": "error"
}
